### ISSUE TITLE
Class tags with same attributes 

### ISSUE THREAD

**Issue by Djmon07** [Anthony-Harvey-tsct/anthony-harvey-tsct.github.io#4]
https://github.com/Anthony-Harvey-tsct/anthony-harvey-tsct.github.io/blob/d53ca7cb24eb8f2aecc5f19914a4a3dab8f66315/styles.css#L58

you could group all the classes together to keep the css cleaner, also you could put them all into one class to make it easier and effect them all with same attributes.

**Comment by zachfedor** [comment]
I agree with @Djmon07. The whole point of classes is to style similar elements. If you see something like this:
```css
.apple {  width: 25%; height: 25%; }
.banana {  width: 25%; height: 25%; }
```
Then you should probably have something like this instead: 
```css
.fruit {  width: 25%; height: 25%; }
```
